### ISSUE TITLE
Fall back to interpreting a response as plain HAL if no `_templates` is present

### ISSUE THREAD

**Issue by odrotbohm** [toedter/hal-explorer#124]
When processing a request that might result in a HAL-FORMS response, most frameworks will have to apply some content negotiation very early in the processing lifecycle. As HAL Explorer prefers HAL-FORMS, the server frameworks might eagerly decide to return HAL-FORMS if they're generally capable of doing so, but the request handling user code ending up being unable to add templates of any kind. Maybe because it doesn't make any sense to provide any.

I know the spec requires the `_templates` property to contain at least one template. That said, it also says:
> If the HAL-FORMS document does not contain this element or the contents are unrecognized or unparsable, the HAL-FORMS document SHOULD be ignored.

I wonder if “ignoring the document” could be interpreted as “treat the document as plain HAL” which would also be in line with this part of the spec:

> This is a backward-compatible, non-standard extension. There is nothing in this format or process pattern that adds breaking changes to the HAL media type itself.

The current effect of returning HAL-FORMS in the `Content-Type` header and not serving any templates is that only `GET` is supported for any of the links returned with the document. Returning HAL in that header allows issuing requests using other HTTP methods, too. In an API that gradually attempts to introduce HAL-FORMS, but can't tweak the returned `Content-Type` header for each of the resources exposed individually, this would be a very helpful change.

**Comment by toedter** [comment]
Thx for reporting this, I'll take a look at it.

**Comment by toedter** [comment]
Now HAL-Explorer checks if a HAL-FORMS document contains _templates and treats it as HAL-Document otherwise. Please check your use cases and re-open if the behavior is not as expected.
