### ISSUE TITLE
OAuth2/login support

### ISSUE THREAD

**Issue by rfelgent** [toedter/hal-explorer#16]
Hi,

since Spring Boot 2.2 the "hal-browser" is marked as deprecated and developers are encouraged to switch to "hal-explorer".

Are there any plans to support (any sort of) login mechanism ? Ideally, Oauth2 would be great. 
Is this feature already available, but I missed it accidently ?!

Greetings

**Comment by toedter** [comment]
Currently, there is no direct support of authorization flows. However, if you are using OAuth2, and you got a token through your own authorization flow already, you could put the bearer token in a link to the HAL-Explorer, like https://chatty42.herokuapp.com/hal-explorer/index.html#theme=Cosmo&hkey0=Authorization&hval0=Bearer%201234&uri=/api/

Then all requests done by the HAL-Explorer are enhanced with the request header "Authorization: Bearer 1234"

Probably I'll add the support of authorization flows in the future, but it is not planned right now.

**Comment by pmoule** [comment]
> Currently, there is no direct support of authorization flows. However, if you are using OAuth2, and you got a token through your own authorization flow already, you could put the bearer token in a link to the HAL-Explorer, like https://chatty42.herokuapp.com/hal-explorer/index.html#theme=Cosmo&hkey0=Authorization&hval0=Bearer%201234&uri=/api/
> Then all requests done by the HAL-Explorer are enhanced with the request header "Authorization: Bearer 1234"

Really great, Kai! You answer my question before I even ask :)
Thanks and best
Patrick

**Comment by rfelgent** [comment]
Hello again,

thx for the quick response! It is good to know, that I didnt overlooked that feature - it's not there yet.

I have doubts that providing sensitive authorization data via query param is a good idea. I would like to start (trigger) login flow from the hal-explorer.

**Comment by toedter** [comment]
> I have doubts that providing sensitive authorization data via query param is a good idea

Yes, we usually use an authenticating reverse proxy (gateway) between our frontends and backends and never expose tokens to the Web browser. But flows like implicit flow are still used in the wild. Then the token is exposed to the browser anyway and putting it in in query data to fill the HAL-Explorer's request headers would not do additional harm.

**Comment by toedter** [comment]
I am not planning to implement any authorization flow directly into HAL-EXplorer. If you see a demand, please open a new issue.

**Comment by vwong** [comment]
Bear in mind though, that if you initialize HAL Explorer this way, the auth headers will be added to the browser history, so you could be accidentally leaking bearer tokens.

**Comment by toedter** [comment]
> Bear in mind though, that if you initialize HAL Explorer this way, the auth headers will be added to the browser history, so you could be accidentally leaking bearer tokens.

that is true, so the bearer tokens should have a decent expiry.
