### ISSUE TITLE
Consider regular expression defined for HAL Forms template properties

### ISSUE THREAD

**Issue by odrotbohm** [toedter/hal-explorer#17]
It would be cool if the form created to capture the properties of a HAL Forms template to verify the expression in `regex` and prevent the form from being submitted unless they match.

**Comment by toedter** [comment]
I just saw that you "undeprecated" `HalFormsConfiguration withPattern(Class<?> type, String pattern)` in Spring HATEOAS.
I will take a look at it. 

Are you planning to also support other HAL-FORMS property attributes like `type`, `max`, `maxLength`, etc. in Spring HATEOAS?
See https://rwcbook.github.io/hal-forms/ in the Properties section for a complete list.

I think it would be a good idea if HAL-Explorer implements input validation based on all available property elements that can be used for input validation.

**Comment by toedter** [comment]
Started implementing this, see https://hypermedia-movies-demo.herokuapp.com/hal-explorer/index.html#theme=Cosmo&uri=https://hypermedia-movies-demo.herokuapp.com/api/movies

Click the + sign. The title is required and the release year has a regex. If you hover over the input fields, you get the error message as tooltip.

Feedback would be appreciated.

**Comment by toedter** [comment]
Implemented HAL-FORMS property contraint validation for required., regex, min, max, maxLwngth, and minLength.
