### ISSUE TITLE
Relative urls are not correctly expanded

### ISSUE THREAD

**Issue by evert** [toedter/hal-explorer#19]
Example:

http://hypermedia-movies-demo.herokuapp.com/hal-explorer/index.html#theme=Cosmo&uri=https://todo-api.curveballjs.org/

To test, do a GET request on one of the links.

(this is probably a stretch, but I _probably_ can't convince you to give [https://github.com/badgateway/ketting](https://github.com/badgateway/ketting) a shot for this project? You might like it and we can combine efforts!)

**Comment by toedter** [comment]
Thx @evert , I will take a look at it.

**Comment by toedter** [comment]
Fixed. You can browse your API now (using the current snapshot of HAL Explorer):
http://hypermedia-movies-demo.herokuapp.com/hal-explorer/index.html#theme=Cosmo&uri=https://todo-api.curveballjs.org/
This will be in the next release.

Related to ketting: I will take a closer look next weekend.

One little thing: todo-api.curveballjs.org/ returns content-type `application/json`, even though it contains `_links`.
