### ISSUE TITLE
<base> disallows deployment into a web server context

### ISSUE THREAD

**Issue by DavidBiesack** [toedter/hal-explorer#2]
After running
```
npm run build -prod
```
I pointed a Tomcat context to the HAL explorer `dist` folder
```
<Context path="/hal-explorer" docBase="/Users/.../path/to/hal-explorer/dist" reloadable="true">
   <Resources allowLinking="true" />
</Context>
```
and opened http://localhost:8080/hal-explorer in my browser, but it failed because of the 
```
  <base href="/">
```
It tries to load http://localhost:8080/scripts.82689310a4d7f41146ed.bundle.js instead of http://localhost:8080/hal-explorer/scripts.82689310a4d7f41146ed.bundle.js

Removing  the`<base>` element from index.html resolves this, and running locally via `npm start` also works on localhost:4200

**Comment by toedter** [comment]
Thanks, I have merged your pull request.
