### ISSUE TITLE
Most links are not showing up with Spring Boot 2.5.0

### ISSUE THREAD

**Issue by eiswind** [toedter/hal-explorer#28]
![Bildschirmfoto von 2021-05-21 13-29-49](https://user-images.githubusercontent.com/1238044/119130582-b30f6e80-ba38-11eb-8823-f8a4ae75985f.png)

I created a simple example with an Entity and a JpaRepository. This works fine in Spring Boot 2.4.6 but does not show POST/DELETE etc links in 2.5.0.

Not sure, this could be also  a data-rest issue :)

**Comment by pmoule** [comment]
@eiswind 
The content-type in your response header is `application/prs.hal-forms+json`.
In this case only GET request is displayed in HAL Explorer.

In case you planned to make a HAL-FORMS example, this seems intended behaviour. 
For a HAL example content-type should be `application/json`.

Best
Patrick

**Comment by toedter** [comment]
This is on purpose with HAl-FORMS media type., since HAL-FORMS provides affordances (_templates) for exactly those use cases.

**Comment by eiswind** [comment]
Thanks for clearing this up! I didn't catch that change.

This must be a new behaviour of data-rest then. I just updated the spring boot version an got this new content-type w/o further changes. I'll have to investigate a little further.

**Comment by toedter** [comment]
Thanks for pointing this out, I will check with latest Spring Data REST versions soon.

**Comment by pmoule** [comment]
> BTW, the media type for HAL is `application/hal+json`

thx, fixed the typo

**Comment by pravinkalekar** [comment]
@eiswind 

> This must be a new behaviour of data-rest then. I just updated the spring boot version an got this new content-type w/o further changes. I'll have to investigate a little further.

Did you find out how to suppress HAL-FORMS support in Spring Data REST or Spring HATEOAS for HAL Explorer to continue working for all HTTP Methods as it was working with previous versions of SpringBoot (2.4.9 earlier)?

**Comment by eiswind** [comment]
@pravinkalekar just set the content-type header to application/hal+json in the ui.

**Comment by djkeh** [comment]
@eiswind

> @pravinkalekar just set the content-type header to application/hal+json in the ui.

I still don't understand how to suppress hal-forms. I couldn't find the location to set the content-type header in the Spring Boot HAL explorer ui. Could you explain with more details to control it?

**Comment by pravinkalekar** [comment]
Use the "Edit Headers" button in the top left corner next to the API URL to set the content-type header.

**Comment by djkeh** [comment]
@pravinkalekar Wow. I couldn't see that button. Thanks!

For those who want more accurate information, in order to get `application/hal+json` content-type response, I can set my request header using `Accept` key.

![image](https://user-images.githubusercontent.com/4949544/132979500-d4d0cc78-6a99-4d63-9d4f-4a5dbac9388d.png)
