### ISSUE TITLE
[Bug] TypeError: this.halFormsProperties is not iterable

### ISSUE THREAD

**Issue by robertsundstrom** [toedter/hal-explorer#37]
## Problem description

**HAL Explorer Version:** v1.0.0

HAL Explorer does not correctly handle a potential lack of ```properties``` for HTTP methods that normally take request bodies.

## Scenario

I have a sample template: 

```json
{
       "_templates": {
          "clear": {
            "title": "Clear all items",
            "method": "POST",
            "contentType": "application/json",
            "target": "/api/carts/2e769b7c-2fff-4830-9beb-737c3a4a65e9/clear"
          }
        }
}
```

When clicking the button in the UI, the request fails in the background:

```js
main-es2015.71f7e9a03e1c3ab8ebcc.js:1 ERROR Error: Uncaught (in promise): TypeError: this.halFormsProperties is not iterable
TypeError: this.halFormsProperties is not iterable
```

## Expected behavior 

It should ignore ```properties``` if there is none defined, regardless of method.

**Comment by toedter** [comment]
Thanks for reporting this, I'll take a look at it asap.
