### ISSUE TITLE
Add option to execute OPTIONS request for a link

### ISSUE THREAD

**Issue by Ickbinet** [toedter/hal-explorer#39]
It would be nice if the explorer had an option where the user can decide if for a single or each link an OPTIONS request should be executed.
The allow response header could be used to enable/disable the request buttons besides the link.

**Comment by toedter** [comment]
That sounds like a good idea, I'll take a look at it.

**Comment by toedter** [comment]
Would you consider this for HAL only? My current assumption for HAL-FORMS is that all the links are GET only, while _templates are used for all affordances that define a specific HTTP method.

**Comment by toedter** [comment]
It is implemented in the current snapshot. You can test it:
For HAL: Chatty API (Spring Data REST Backend): https://chatty42.herokuapp.com/hal-explorer/index.html#theme=Cosmo&layout=3&httpOptions=true&uri=/api/
For HAL-FORMS: Movies API (Spring HATEOAS Backend): https://hypermedia-movies-demo.herokuapp.com/hal-explorer/index.html#theme=Cosmo&httpOptions=true&uri=https://hypermedia-movies-demo.herokuapp.com/api/movies

**Comment by Ickbinet** [comment]
So it is activated by httpOptions=true in the URL?

**Comment by toedter** [comment]
yes, there is also a menu entry that you can select in the Settings menu.

**Comment by toedter** [comment]
released
