### ISSUE TITLE
Configuring an custom Accept header should override defaults

### ISSUE THREAD

**Issue by odrotbohm** [toedter/hal-explorer#4]
The application of custom headers currently adds default `Accept` headers no matter what and appends all headers configured. This renders defining a custom Accept header not taking effect, especially as the default contains `*/*`.

If you define `foo/bar` as custom accept header and the server is able to produce both one of the defaults *and* the custom media type, it would still render the default one as it matches first.

https://github.com/toedter/hal-explorer/blob/c84c14787ea3edc01ccd1db9f9734d543b660f4f/src/app/request/request.service.ts#L227-L236

**Comment by toedter** [comment]
Would it be sufficiant to remove the `*/*` or would it even better if '`Accept': 'application/hal+json, application/json, */*' `would only be added if there is no Accept header in the list of custom headers?

**Comment by odrotbohm** [comment]
If I configure an `Accept` header explicitly, I'd expect it to submit only the value(s) I defined.

**Comment by toedter** [comment]
Ok, then I will implenet it this way: I parse all custom headers. If I don't find header.toLowerCase === 'accept' then I add `'Accept': 'application/hal+json, application/json, */*' 
`

**Comment by toedter** [comment]
Fixed 

https://github.com/toedter/hal-explorer/blob/94d59bf676aa986fcb53cd2c2e4a42509ea39a87/src/app/request/request.service.ts#L227-L241
