### ISSUE TITLE
HAL-FORMS contentType property is ignored

### ISSUE THREAD

**Issue by Ickbinet** [toedter/hal-explorer#40]
A HAL-FORMS contentType property is ignored, Explorer always sends application/json. application/x-www-form-urlencoded should be supported too.

**Comment by toedter** [comment]
Thx for reporting this, I#ll take a look at it.

**Comment by toedter** [comment]
Please check if it works as expected.

**Comment by Ickbinet** [comment]
Looks like you now send the correct content-type header, but the body is still always json?

**Comment by toedter** [comment]
released
