### ISSUE TITLE
Response is always expected as json

### ISSUE THREAD

**Issue by Ickbinet** [toedter/hal-explorer#41]
Response types other than json are always handled as error.
For other response types an iframe could be used, hoping the browser can handle it.

**Comment by toedter** [comment]
Could you please give a concrete example?

**Comment by Ickbinet** [comment]
The Server returns content-type: text/plain;charset=ISO-8859-1

The Explorer says:
"Http failure during parsing for https://..."
{
  "error": {},
  "text": "--response body here--"
}

**Comment by toedter** [comment]
Currently HAL Explorer supports only JSON responses. If I find the time, I'll look into it.

**Comment by toedter** [comment]
I thought about this, but the purpose of HAL explorer is to explore HAL/HAL-FORMS-based APIs. So if a server returns something else, HAL explorer returns an error, complaining that the content cannot be parsed. But I get your point that a HAL link could return anything, even a picture. But it would be overengineering to have a proper display, response for all possible responses. It's like if you use a picture viewer that expects a picture format and you feed it with another binary format.

So I am not planning to fix this behavior.
If a fix would be important for you, please re-open.
