### ISSUE TITLE
Support for request content types other than json

### ISSUE THREAD

**Issue by Ickbinet** [toedter/hal-explorer#43]
At the moment only json as request body content type is supported.

If a hal form does not support this content-type the form should be not available in the hal forms section or it should not be submittable in the form dialog (with a hint explaining that only json is supported).

Future goal:

Support FormData (application/x-www-form-urlencoded and multipart/form-data) via https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects.

**Comment by toedter** [comment]
I start investigating. Sorry for the delay, I was super busy with other things.

**Comment by toedter** [comment]
I close this for now since I do not find the time for it, please re-open if this becomes urgent.
