### ISSUE TITLE
Path variables being inserted into template as request variable (querystring)

### ISSUE THREAD

**Issue by colin-young** [toedter/hal-explorer#5]
HAL-Explorer: v0.10.0

Given a URI template:

    http://localhost:8081/v1/customer/{customerId}

The template is expanded as:

    http://localhost:8081/v1/customer/?customerId=12345

Where I am expecting (and so is Spring-Hateoas):

    http://localhost:8081/v1/customer/12345

**Comment by toedter** [comment]
Thanks for reporting, I will take a at it.

**Comment by toedter** [comment]
fixed, will be in the next release.

**Comment by colin-young** [comment]
Confirmed. Thanks!
