### ISSUE TITLE
HAL-Forms not using prompt from _templates property

### ISSUE THREAD

**Issue by colin-young** [toedter/hal-explorer#6]
HAL-Explorer: v0.10.0

(I recognize that you _just_ added HAL Forms and it's probably not done yet...)

```
// ...
"_templates": {
          "default": {
            "title": null,
            "method": "patch",
            "contentType": "",
            "properties": [ { ... },
              {
                "name": "lastName",
                "prompt": "Last Name",
                "regex": "[a-zA-Z]*",
                "required": false
              }, { ... }, ...
            ]
// ...
```

When I open the HTTP Request Input dialog the HAL-Forms Properties labels are all empty.

**Comment by colin-young** [comment]
I see in your Heroku demo you _are_ showing the prompts, but I can't figure out where you're getting them from.

**Comment by toedter** [comment]
Thanks for reporting. In the Chatty demo, I don't use HAL-FORMS but the Spring profile to populate the labels, but I have another demo for HAL-FORMS. If you take a look at http://hypermedia-movies-demo.herokuapp.com/hal-explorer/index.html#theme=Cosmo&url=http://hypermedia-movies-demo.herokuapp.com/api/movies/1

HAL Explorer marks the self link with HAL Forms, and offers only the affordances like put and delete. If you click on PUT than you see that all the labels are initialized using the HAL-FORMS prompt values.

Could you provide me with an example that I can reproduce the behavior you described?

**Comment by toedter** [comment]
I found another issue related to that, will start working on it soon. The current HAL Explorer implementation implementation always uses _templates.default, which is wrong. The fix would  search for the corresponding "method" and then map those properties.

**Comment by colin-young** [comment]
I was using the PATCH method. I'll check out the PUT and see what I get, but I'm out of the office for the next week (and actually taking time off). Just as an FYI, I am using your reflection method you provided to me in https://github.com/spring-projects/spring-hateoas/issues/979 to set the prompt.

**Comment by colin-young** [comment]
So I did see this working in 0.10.0 and now I'm having trouble getting the form to appear in 0.11.0, but I think that is user error.

**Comment by toedter** [comment]
Could you send me the request body, then I could check. One thing that I changed in 0.11.0: I now check if there is a response header `content-type` that starts with the HAL-FORMS media type `application/prs.hal-forms+json` to recognize if the response is HAL-FORMS. Does your server response contain the correct content type?

**Comment by colin-young** [comment]
Yeah, it does. It's started working now. I'm pretty sure it was user error. I didn't look closely enough at the changes another developer made and ended up with 2 different controllers registered to handle the PATCH request. It worked for a while until I tried to actually call it. Seems as though the affordances were able to generate something, but not the correct thing. Now that I've fixed that it's all working.

On the other hand, I am struggling with how to represent a PATCH, other than just making everything except the identifier optional. Is that normally how it's done? Other APIs we're using RFC-6902, which doesn't really fit into the HAL-Forms model.

**Comment by toedter** [comment]
Here is an example how I implemented a patch with Spring HATEOAS: https://hypermedia-movies-demo.herokuapp.com/hal-explorer/index.html#theme=Cosmo&uri=https://hypermedia-movies-demo.herokuapp.com/api/movies/1

Please wait a little bit, Heroku takes a while to start up the service when you call the url.
