### ISSUE TITLE
Double requests when navigating APIs with HAL explorer

### ISSUE THREAD

**Issue by pmoule** [toedter/hal-explorer#60]
Hi Kai

When working with HAL explorer, I regulary see double requests in my logs and Network tab in DevTools.

**Example**
Open [HAL Explorer Demo (1.1.1)](https://toedter.github.io/hal-explorer/release/hal-explorer/#theme=Cosmo&uri=examples/examples.hal-forms.json) and open e.g. Chrome's Network tab in DevTools.
Trigger the GET request via GET button for relation _hal-movies_. You'll see two requests. One after another. As far as I can see both are identical - same behaviour in Firefox.

Same when you e.g paste `https://toedter.github.io/hal-explorer/release/hal-explorer/examples/movies.hal.json` into the input field and push the _Go!_ button. Two requests visible in Network tab after that. Pushing the _Go!_ button a second time only results in a single request.

My RESTful APIs navigated with HAL explorer regularly show two identical log entries for request. Can you please clarify whether this is intended or a bug.

![image](https://user-images.githubusercontent.com/18518641/204353661-2556793a-0c4f-4115-b57f-4354435be5ca.png)

Thanks & best wishes
Patrick

**Comment by toedter** [comment]
Thanks for reporting this. It seems to be a bug, I will take a look at it asap.

**Comment by toedter** [comment]
This happened because 

- a click on the Go! button starts a request
- and changes the hash location to uri=<new URL>
- that triggered a new request with the same URI

I fixed in explicitely not reacting on a hash location change after doing a request and changing the hash location.

**Comment by pmoule** [comment]
Thanks a lot for providing a fix.
Best wishes
