### ISSUE TITLE
Relation named "curies [0] in "Links" section 

### ISSUE THREAD

**Issue by pfichtner** [toedter/hal-explorer#61]
When running backends having curis, e.g. https://github.com/odrotbohm/spring-restbucks, there is a relation named "curies [0] in the "Links" section. 

![hal-explorer-curis-issue](https://user-images.githubusercontent.com/1958485/205963953-57b2939a-a3ae-4a3d-894c-cb08f3620d8c.png)

All relations in the "restbucks" curi namespace have a (working) document icon (with working link on it). 
Shouldn't be the "curies" relation filtered from the "links" section since it's not a real link relation but one with a special meaning? 

Response body is/was
```
{
  "_links": {
    "restbucks:orders": {
      "href": "http://localhost:8080/orders{?page,size,sort,projection}",
      "templated": true,
      "title": "Access or create orders"
    },
    "profile": {
      "href": "http://localhost:8080/profile"
    },
    "curies": [
      {
        "href": "http://localhost:8080/docs/{rel}.html",
        "name": "restbucks",
        "templated": true
      }
    ]
  }
}
```

**Comment by pfichtner** [comment]
Thanks @toedter, so if this is the intended beahviour the issue could/should be closed, right?

**Comment by toedter** [comment]
yes :)
