### ISSUE TITLE
Only "GET"-Buttons in "Links"-Section if there are HAL-Form templates

### ISSUE THREAD

**Issue by pfichtner** [toedter/hal-explorer#62]
When runing https://github.com/odrotbohm/spring-restbucks without affordance HAL-Explorer (content-type `application/prs.hal-forms+json`) renders the links as followed
![hal-forms-1](https://user-images.githubusercontent.com/1958485/205970216-b9f3c03f-b6c2-446b-94d8-bc570a0de3fe.png)

but when using affordance (content-type `application/hal+json`), "HAL-FORMS Template Elements" are added correctly, but all link in the above "Links"-Section lose all there buttons beside the "GET"-Buttons. 
![hal-forms-2](https://user-images.githubusercontent.com/1958485/205971186-007a8e0d-b13f-484e-af0c-b47506a6c053.png)

**Comment by toedter** [comment]
yes, this is on purpose. If HAL-FORMS is used, _templates would be expected with defined HTTP verbs for non-GET request. All links are treated as only accable via GET. I'll take a look at Olli's example.

**Comment by pfichtner** [comment]
> yes, this is on purpose. If HAL-FORMS is used, _templates would be expected with defined HTTP verbs for non-GET request. 

This is what I expected and what's working correctly. 

> All links are treated as only accable via GET. 

Is this a recommendation of the HAL-Forms draft or does the draft specify this in any way? I guessed that it's not a bug but a feature as I would have argued like you. 

> I'll take a look at Olli's example.

Thanks for that. In Olli's example you see that this is problematic because since Olli added the payment affordance it's no longer possible to update or cancel an existing order using HAL-Explorer.

**Comment by toedter** [comment]
I think RestBucks is inconsistent here. It uses a mix of HAL and HAL-FORMS. But I am thinking of an option to relax the visible HTTP verbs for links when using HAL-FORMS.

**Comment by toedter** [comment]
Clsing it since I don't plan to change this behaviour. If you have real more use cases that require to enable all HTTP verbes for links (and using HAL-FORMS), plese re-open.

**Comment by pfichtner** [comment]
I can understand that you don't want to change this default behaviour. 
Would be some env or startup switch to (re-)enable all buttons in such cases be an option? So inconsistent behavioral application would still be usable/exlorable.

**Comment by toedter** [comment]
yes, that would be something I could do, like providing a new Option. I re-open this issue.

**Comment by toedter** [comment]
Implemented a new setting in the current snapshot. Please try out https://toedter.github.io/hal-explorer/snapshot/hal-explorer/#theme=Cosmo&allHttpMethodsForLinks=true&uri=https://toedter.github.io/hal-explorer/snapshot/hal-explorer/examples/index.hal-forms.json

and give feedback.

**Comment by pfichtner** [comment]
Thanks so much and a happy new year!

**Comment by toedter** [comment]
Then I close this issue.
