### ISSUE TITLE
Add support for property regex

### ISSUE THREAD

**Issue by colin-young** [toedter/hal-explorer#7]
Use regex (if present) to create/put/patch form elements validation, now that Spring-HATEOAS is supplying it.

I'd be happy to contribute a PR, but I'd need a bit of help orienting myself in the Angular code (I'm a React guy and I've managed to avoid ever having to do any real work in Angular up until now).

**Comment by toedter** [comment]
Thx Colin. Sorry, I don't understand what you mean. If this is still important, please re-open and give more details.
